# Generated by Django 3.2 on 2021-06-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
